language: java
jdk:
    -openjdk11
    
addons:
    sonarcloud:
        organization: valevalefra
        token: 824521aa75299bbc361095158a0bf3ebc4e502b9
script:
    - ant build
    - sonar-scanner